--*模具基本資料 修改
BEGIN TRAN
update   MTMMB  set   MTMMB.MB002    =   INVMB.MB002 
,MTMMB.MB201= CASE WHEN SUBSTRING(MTMMB.MB202,11,1)='P' THEN '非組合模'  WHEN SUBSTRING(MTMMB.MB202,11,1)='D' THEN '非組合模'  WHEN SUBSTRING(MTMMB.MB202,11,1)='N' THEN '非組合模'  WHEN SUBSTRING(MTMMB.MB202,11,1)='0' THEN '組合模'  END 
,MTMMB.MB200= CASE WHEN SUBSTRING(MTMMB.MB202,11,1)='P' THEN '上沖' WHEN SUBSTRING(MTMMB.MB202,11,1)='D' THEN '下模' WHEN SUBSTRING(MTMMB.MB202,11,1)='N' THEN '下沖'  WHEN SUBSTRING(MTMMB.MB202,11,1)='0' THEN '組合模'  END 
,MTMMB.MODIFIER=3678,MODI_DATE=CONVERT(varchar(100), GETDATE(), 112)
,MODI_TIME=LEFT(CONVERT (time, GETDATE()),8),MODI_AP='HUAN' 
from   MTMMB,INVMB where  MTMMB.MB047='N' AND MTMMB.MB002 ='' AND MB202 !='' AND MTMMB.MB202=INVMB.MB001
ROLLBACK

--*模具基本資料 改錯時，修改回去
BEGIN TRAN
update   MTMMB  set   MTMMB.MB002    =NULL 
,MTMMB.MB201= NULL 
,MTMMB.MB200= NULL  
,MODI_DATE=NULL,MODI_AP=NULL,MODI_TIME=NULL,MODIFIER=NULL
from   MTMMB,INVMB where  MTMMB.MB047='N' AND MTMMB.MB002 ='' AND MB202 !='' AND MTMMB.MB202=INVMB.MB001
ROLLBACK
COMMIT



select * from MTMMB where MTMMB.MB047='N' AND MTMMB.MB002 ='' AND MB202 !='' 

SELECT * FROM INVMB WHERE MB001 LIKE 'H084C0%'

--erp模具拋轉smes的紀錄
select * from [dbo].ERPII_SMES_MTMMB order by TDATE desc


SELECT * FROM sys.sysindexes WHERE id=object_id('MTMMB') and  name='PK_MTMMB'
DBCC SHOWCONTIG(MTMMB)


