--產品更換流程時，需重新INSERT
--

--SELECT  *  FROM	tblPRDAccessory
--SELECT  *  FROM TBLPRSPROCESSBASIS
--SELECT  *  FROM	TBLEQPACCESSORYBASIS 

--SELECT  *  FROM	TBLPRSNODEBASIS
/*
WITH T1 AS(
SELECT  CASE WHEN LEN(NODENO)=2 THEN SUBSTRING(NODENO,2,1) 
			 WHEN LEN(NODENO)=3 THEN SUBSTRING(NODENO,2,2) 
			 WHEN LEN(NODENO)=4 THEN SUBSTRING(NODENO,2,1)
			 ELSE NODENO END MIN
			 ,CASE WHEN LEN(NODENO)=4 THEN SUBSTRING(NODENO,4,1) END MAX
			 ,B.*  
FROM	TBLPRSPROCESSBASIS A 
LEFT JOIN TBLPRSNODEBASIS B ON A.PROCESSNO=B.PROCESSNO AND A.PROCESSVERSION=B.PROCESSVERSION
WHERE A.CURVERSION=1 AND  NODETYPE =0 AND NODENO LIKE '%P%' AND NODENO NOT LIKE '%[A-Oa-oQ-Zq-z]%'
--ORDER BY NODENO
)
*/

--太晚入庫、核准、綁定，壽命計算就會不准
--應該客製P2都不用上模具?


BEGIN TRAN INSERT INTO tblPRDAccessory (PRODUCTNO, ACCESSORYTYPE, ACCESSORYNO, PRODUCTVERSION, OPNO ,AccessoryCategory)
SELECT '4'+LEFT(ACCESSORYNO,6) PRODUCTNO, ACCESSORYTYPE, ACCESSORYNO, CURVERSION
--, SUBSTRING(AccessoryName,CHARINDEX('-',AccessoryName)+1,1) OPNO
,B.NODENO
,AccessoryCategory
--SELECT *
FROM TBLEQPACCESSORYBASIS A
LEFT JOIN (SELECT  CASE WHEN LEN(NODENO)=2 THEN SUBSTRING(NODENO,2,1) --若作業站為2碼：P2，則第一個作業站為2
			 WHEN LEN(NODENO)=3 THEN SUBSTRING(NODENO,2,2)  --若作業站為3碼：P10，則第一個作業站為10
			 WHEN LEN(NODENO)=4 THEN SUBSTRING(NODENO,2,1)  --若作業站為4碼：P2-5，則第一個作業站為2
			 WHEN LEN(NODENO)=5 THEN SUBSTRING(NODENO,2,1)  --若作業站為4碼：P2-10，則第一個作業站為2
			 ELSE NODENO END MIN
			 ,CASE WHEN LEN(NODENO)=4 THEN SUBSTRING(NODENO,4,1)   --若作業站為2碼：P2，則最後一個作業站為2
					WHEN LEN(NODENO)=5 THEN SUBSTRING(NODENO,4,2)   --若作業站為3碼：P10，則最後一個作業站為10
					WHEN LEN(NODENO)=2 THEN SUBSTRING(NODENO,2,1)   --若作業站為4碼：P2-5，則最後一個作業站為5
					WHEN LEN(NODENO)=3 THEN SUBSTRING(NODENO,2,2)   --若作業站為5碼：P2-10，則最後一個作業站為10
			END MAX
			 ,B.*  
			FROM	TBLPRSPROCESSBASIS A --流程基本資料表
			LEFT JOIN TBLPRSNODEBASIS B ON A.PROCESSNO=B.PROCESSNO AND A.PROCESSVERSION=B.PROCESSVERSION  --流程節點基本資料表 NODETYPE→ 0: OP  1: Sub Process  6: And Group  7: Or Group  8: Start  9: End

			WHERE A.CURVERSION=1 AND  NODETYPE =0  --條件：是當前流程，NODETYPE 為 0: OP
			AND NODENO LIKE '%P%' AND NODENO NOT LIKE '%[A-Oa-oQ-Zq-z]%') B --只有作業站編號為'P+數字'，才是需要模具的鍛打站
ON B.PROCESSNO='4'+LEFT(A.ACCESSORYNO,6) --第一遍ON  4M058C0 ='4'+LEFT(M058C0-02-D01,6)  
--第二遍ON 模具名稱M058C0-3-D01 要綁到產品4M058C0  的P3作業站
AND B.MIN<= SUBSTRING(AccessoryName,CHARINDEX('-',AccessoryName)+1,1) --作業站P3  MIN=3   
AND B.MAX>=SUBSTRING(AccessoryName,CHARINDEX('-',AccessoryName)+1,1)  --作業站P3  MAX=3
WHERE ISSUESTATE=2  --2 已簽核
--AND ACCESSORYNO LIKE '%-%' AND AccessoryName LIKE '%[PDN]%' AND AccessoryName LIKE '%[-]%' AND ACCESSORYCATEGORY='非組合模'
AND ACCESSORYNO+B.NODENO NOT IN(SELECT ACCESSORYNO+OPNO FROM tblPRDAccessory) --排除已經綁好的資料
ORDER BY LEN(B.NODENO)
--AND ACCESSORYNO NOT IN(SELECT ACCESSORYNO FROM tblPRDAccessory) 
ROLLBACK
COMMIT




/*
--BEGIN TRAN INSERT INTO tblPRDAccessory (PRODUCTNO, ACCESSORYTYPE, ACCESSORYNO, PRODUCTVERSION, OPNO ,AccessoryCategory)
SELECT PROCESSNO, ACCESSORYTYPE, ACCESSORYNO, CURVERSION
--, SUBSTRING(AccessoryName,CHARINDEX('-',AccessoryName)+1,1) OPNO
,B.NODENO
,AccessoryCategory
--SELECT ,*
FROM TBLEQPACCESSORYBASIS A
LEFT JOIN (SELECT  CASE WHEN LEN(NODENO)=2 THEN SUBSTRING(NODENO,2,1) 
			 WHEN LEN(NODENO)=3 THEN SUBSTRING(NODENO,2,2) 
			 WHEN LEN(NODENO)=4 THEN SUBSTRING(NODENO,2,1)
			 WHEN LEN(NODENO)=5 THEN SUBSTRING(NODENO,2,1)
			 ELSE NODENO END MIN
			 ,CASE WHEN LEN(NODENO)=4 THEN SUBSTRING(NODENO,4,1)
					WHEN LEN(NODENO)=5 THEN SUBSTRING(NODENO,4,2)
					WHEN LEN(NODENO)=2 THEN SUBSTRING(NODENO,2,1)
					WHEN LEN(NODENO)=3 THEN SUBSTRING(NODENO,2,2)
			END MAX
			 ,B.*  
			FROM	TBLPRSPROCESSBASIS A 
			LEFT JOIN TBLPRSNODEBASIS B ON A.PROCESSNO=B.PROCESSNO AND A.PROCESSVERSION=B.PROCESSVERSION
			--共用模具不只P2
			WHERE A.CURVERSION=1 AND  NODETYPE =0 AND NODENO LIKE 'P%' AND NODENO NOT LIKE '%[A-Oa-oQ-Zq-z]%'
			AND A.PROCESSNO+B.NODENO NOT IN(SELECT ACCESSORYNO+OPNO FROM tblPRDAccessory)
			) B 
			
ON B.MIN<= SUBSTRING(AccessoryName,CHARINDEX('-',AccessoryName)+1,1) AND B.MAX>=SUBSTRING(AccessoryName,CHARINDEX('-',AccessoryName)+1,1)
WHERE ISSUESTATE=2 AND ACCESSORYNO LIKE '%-%' AND AccessoryName LIKE '%共用%' AND ACCESSORYCATEGORY='非組合模'
--AND ACCESSORYNO+B.NODENO NOT IN(SELECT ACCESSORYNO+OPNO FROM tblPRDAccessory) 
ORDER BY LEN(B.NODENO)
--AND ACCESSORYNO NOT IN(SELECT * FROM tblPRDAccessory) 
ROLLBACK